let cards = {};

cards.selectedCards = [];
cards.usedCards = [];
cards.currentCards = [];
cards.allTheCards = [
  {color: 'red', selectColor: 'green', number: 1, fill: 'empty', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/1-green-oval.png'), id: 1},
  // {color: 'red', selectColor: 'green', number: 2, fill: 'empty', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 2},
  // {color: 'red', selectColor: 'green', number: 3, fill: 'empty', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 3},
  // {color: 'red', selectColor: 'green', number: 1, fill: 'shaded', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 4},
  // {color: 'red', selectColor: 'green', number: 2, fill: 'shaded', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 5},
  // {color: 'red', selectColor: 'green', number: 3, fill: 'shaded', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 6},
  // {color: 'red', selectColor: 'green', number: 1, fill: 'full', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 7},
  // {color: 'red', selectColor: 'green', number: 2, fill: 'full', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 8},
  // {color: 'red', selectColor: 'green', number: 3, fill: 'full', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 9},
  // {color: 'green', selectColor: 'green', number: 1, fill: 'empty', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 10},
  // {color: 'green', selectColor: 'green', number: 2, fill: 'empty', shape: 'diamond', img: require('/Users/michaelmcgough/Desktop/Coding/SideProjects/SetProject/cardImages/1-green-oval.png'), id: 11}
  // {color: 'green', selectColor: 'green', number: 3, fill: 'empty', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 12},
  // {color: 'green', selectColor: 'green', number: 1, fill: 'shaded', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 13},
  // {color: 'green', selectColor: 'green', number: 2, fill: 'shaded', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 14},
  // {color: 'green', selectColor: 'green', number: 3, fill: 'shaded', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 15},
  // {color: 'green', selectColor: 'green', number: 1, fill: 'full', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 16},
  // {color: 'green', selectColor: 'green', number: 2, fill: 'full', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 17},
  // {color: 'green', selectColor: 'green', number: 3, fill: 'full', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 18},
  // {color: 'purple', selectColor: 'green', number: 1, fill: 'empty', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 19},
  // {color: 'purple', selectColor: 'green', number: 2, fill: 'empty', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 20},
  // {color: 'purple', selectColor: 'green', number: 3, fill: 'empty', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 21},
  // {color: 'purple', selectColor: 'green', number: 1, fill: 'shaded', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 22},
  // {color: 'purple', selectColor: 'green', number: 2, fill: 'shaded', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 23},
  // {color: 'purple', selectColor: 'green', number: 3, fill: 'shaded', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 24},
  // {color: 'purple', selectColor: 'green', number: 1, fill: 'full', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 25},
  // {color: 'purple', selectColor: 'green', number: 2, fill: 'full', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 26},
  // {color: 'purple', selectColor: 'green', number: 3, fill: 'full', shape: 'diamond', img: './cardImages/1-green-oval.png', id: 27},

  // {color: 'red', number: 1, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'red', number: 2, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'red', number: 3, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'red', number: 1, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'red', number: 2, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'red', number: 3, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'red', number: 1, fill: 'full', shape: 'oval', img: ''},
  // {color: 'red', number: 2, fill: 'full', shape: 'oval', img: ''},
  // {color: 'red', number: 3, fill: 'full', shape: 'oval', img: ''},
  // {color: 'green', number: 1, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'green', number: 2, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'green', number: 3, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'green', number: 1, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'green', number: 2, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'green', number: 3, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'green', number: 1, fill: 'full', shape: 'oval', img: ''},
  // {color: 'green', number: 2, fill: 'full', shape: 'oval', img: ''},
  // {color: 'green', number: 3, fill: 'full', shape: 'oval', img: ''},
  // {color: 'purple', number: 1, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'purple', number: 2, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'purple', number: 3, fill: 'empty', shape: 'oval', img: ''},
  // {color: 'purple', number: 1, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'purple', number: 2, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'purple', number: 3, fill: 'shaded', shape: 'oval', img: ''},
  // {color: 'purple', number: 1, fill: 'full', shape: 'oval', img: ''},
  // {color: 'purple', number: 2, fill: 'full', shape: 'oval', img: ''},
  // {color: 'purple', number: 3, fill: 'full', shape: 'oval', img: ''},
  //
  // {color: 'red', number: 1, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'red', number: 2, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'red', number: 3, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'red', number: 1, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'red', number: 2, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'red', number: 3, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'red', number: 1, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'red', number: 2, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'red', number: 3, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'green', number: 1, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'green', number: 2, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'green', number: 3, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'green', number: 1, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'green', number: 2, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'green', number: 3, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'green', number: 1, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'green', number: 2, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'green', number: 3, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 1, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 2, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 3, fill: 'empty', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 1, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 2, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 3, fill: 'shaded', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 1, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 2, fill: 'full', shape: 'rectangle', img: ''},
  // {color: 'purple', number: 3, fill: 'full', shape: 'rectangle', img: ''}
];

export default cards;
